
spring.config.import: optional:file:../config/local-properties.yml;classpath:git.properties,sm://

env:
  db:
    name: ${sm://${DB_NAME_SECRET_ID}}
    password: ${sm://${DB_PASSWORD_SECRET_ID}}
    user: ${sm://${DB_USER_SECRET_ID}}

spring:
  cloud:
    gcp:
      secretmanager:
        enabled: true
      core:
        enabled: true
      project-id: ${GCP_PROJECT_ID}
