gcpProject: broad-juniper-prod
gcpRegion: us-central1
adminUrl: juniper-cmi.org
deploymentZone: prod
replicas: 3
dsmUrl: https://dsm.datadonationplatform.org/dsm
dsmIssuer: juniper.terra.bio
# "portals" is used only to generate the admin certificate (without wildcards):
# e.g. for sandbox.demo.juniper-cmi.org, irb.demo.juniper-cmi.org, etc.
# any addition to this list will require a short downtime for the admin site while the new
# certificate is issued.
portals:
  - demo
  - ourhealth
  - gvasc
  - atcp
  - hearthive
  - trccproject
  - rgp
  - cmi
  - pedihcc

# we have a maximum of 15 certificates per-ingress. since we have 1 admin certificate,
# we have a maximum of 14 study certificates in this list.
# if we need more, we will need to split into multiple ingresses (which costs money).
# where possible, group multiple portals into a single certificate. this would mean
# downtime for all URLs in a group when a new URL is added, but that should be rare.
studyCertificates:
  - groupName: demo
    urls:
      - juniperdemostudy.org
  - groupName: ourhealth
    urls:
      - ourhealthstudy.org
  - groupName: gvasc
    urls:
      - gvascstudy.org
  - groupName: hearthive
    urls:
      - thehearthive.org
  - groupName: cmi
    urls:
      - trccproject.org
      - pedihccproject.org

b2c:
  admin:
    clientId: f02b3816-af49-4a78-a2a5-b929c78a6c47
    tenantName: broadjuniperadmin
    policyName: B2C_1A_ddp_admin_signup_signin_admin-prod
  portals:
    ourhealth:
      tenantName: ourhealthstudy
      clientId: 810055b4-eafc-488e-bc9c-eaa8dd759685
      policyName: B2C_1A_ddp_participant_signup_signin_ourhealth-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_ourhealth-prod
    hearthive:
      tenantName: hearthive
      clientId: ede6cbb1-a2c3-44c0-9a8a-496d48d6f307
      policyName: B2C_1A_ddp_participant_signup_signin_hearthive-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_hearthive-prod
    gvasc:
      tenantName: gvascprod
      clientId: 84192db4-8a68-4f9c-9bd0-b104a24f62f9
      policyName: B2C_1A_ddp_participant_signup_signin_gvasc-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_gvasc-prod
    atcp:
      tenantName: juniperatcp
      clientId: 0ec0e7c0-8db5-46c0-aac8-474c12521058
      policyName: B2C_1A_ddp_participant_signup_signin_atcp-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_atcp-prod
    demo:
      tenantName: juniperdemoprod
      clientId: 895c5f41-5a84-4863-b34c-c84d297006e3
      policyName: B2C_1A_ddp_participant_signup_signin_demo-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_change_password_demo-prod
    trccproject:
      tenantName: trccproject
      clientId: 882e287c-8586-456e-8004-b7ff16da3578
      policyName: B2C_1A_ddp_participant_signup_signin_trcc-prod
      changePasswordPolicyName: B2C_1A_ddp_participant_signup_signin_trcc-prod
gcsFileStorageBuckets:
  unscanned: juniper-participant-documents-prod-unscanned
  clean: juniper-participant-documents-prod-clean
  quarantined: juniper-participant-documents-prod-quarantined
