openapi: 3.0.3
info:
  title: Pearl Admin API
  description: API for portal and study management
  version: 0.0.1
paths:
  /status:
    get:
      summary: Check status of the service
      tags: [ public ]
      operationId: getStatus
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SystemStatusResponse'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/SystemStatusResponse'

  /version:
    get:
      summary: Get version info of the deployed service
      tags: [ public ]
      operationId: getVersion
      security: [ ]
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionProperties'
        '404':
          description: "Version not configured"
        '500':
          $ref: '#/components/responses/ServerError'

  /api/portals/v1/{portalShortcode}/env/{envName}:
    get:
      summary: Gets the portal object
      tags: [ portal ]
      operationId: get
      parameters:
        - { name: portalShortcode, in: path, required: true, schema: {type: string} }
        - { name: envName, in: path, required: true, schema: {type: string} }
      responses:
        '200':
          description: portal object
          content: { application/json: { schema: { type: object }}}
        '500':
          $ref: '#/components/responses/ServerError'
  /api/portals/v1/{portalShortcode}/env/{envName}/preReg/{surveyStableId}/{surveyVersion}:
    post:
      summary: Submits a preregistration survey
      tags: [ preregistration ]
      operationId: createAnonymous
      parameters:
        - { name: portalShortcode, in: path, required: true, schema: { type: string } }
        - { name: envName, in: path, required: true, schema: { type: string } }
        - { name: surveyStableId, in: path, required: true, schema: { type: string } }
        - { name: surveyVersion, in: path, required: true, schema: { type: integer } }
      requestBody:
        content:
          application/json:
            schema: {type: object}
      responses:
        '200':
          description: preregistration response
          content: { application/json: { schema: { type: object } } }
        '500':
          $ref: '#/components/responses/ServerError'
  /api/portals/v1/{portalShortcode}/env/{envName}/preReg/{preRegResponseId}/confirm:
    get:
      summary: Confirms a preregistration id
      tags: [ preregistration ]
      operationId: confirm
      parameters:
        - { name: portalShortcode, in: path, required: true, schema: { type: string } }
        - { name: envName, in: path, required: true, schema: { type: string } }
        - { name: studyShortcode, in: path, required: true, schema: { type: string } }
        - { name: preRegResponseId, in: path, required: true, schema: { type: string, format: uuid} }
      responses:
        '200':
          description: preregistration response
          content: { application/json: { schema: { type: object } } }
        '500':
          $ref: '#/components/responses/ServerError'
  /api/portals/v1/{portalShortcode}/env/{envName}/register:
    post:
      summary: Submits a registration survey
      tags: [ registration ]
      operationId: register
      parameters:
        - { name: portalShortcode, in: path, required: true, schema: { type: string } }
        - { name: envName, in: path, required: true, schema: { type: string } }
        - { name: preRegResponseId, in: query, required: false, schema: { type: string, format: uuid } }
      requestBody:
        content:
          application/json:
            schema: { type: object }
      responses:
        '200':
          description: preregistration response
          content: { application/json: { schema: { type: object } } }
        '500':
          $ref: '#/components/responses/ServerError'
  /api/portals/v1/{portalShortcode}/env/{envName}/siteImages/{shortcodeOrId}:
    get:
      summary: Returns the binary image data for the image of the given shortcode
      tags: [ siteImage ]
      operationId: get
      parameters:
        - { name: portalShortcode, in: path, required: true, schema: { type: string } }
        - { name: envName, in: path, required: true, schema: { type: string } }
        - { name: shortcodeOrId, in: path, required: true, schema: { type: string } }
      responses:
        '200':
          description: image data
          content:
            image/*: # see https://superuser.com/questions/979135/is-there-a-generic-mime-type-for-all-image-files
              schema:
                type: string
                format: binary
        '500':
          $ref: '#/components/responses/ServerError'

components:
  responses:
    SystemStatusResponse:
      description: A JSON description of the subsystems and their statuses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

    # Error Responses
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    PermissionDenied:
      description: Permission denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    NotFound:
      description: Not found (or unauthorized)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

  schemas:
    ErrorReport:
      type: object
      required: [ message, statusCode ]
      properties:
        message:
          type: string
        statusCode:
          type: integer

    SystemStatus:
      required: [ ok, systems ]
      type: object
      properties:
        ok:
          type: boolean
          description: whether any system(s) need attention
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    VersionProperties:
      type: object
      properties:
        gitTag:
          type: string
        gitHash:
          type: string
        github:
          type: string
        build:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: [ ]
