databaseChangeLog:
  - changeSet:
      id: "dsm_env_config"
      author: dbush
      changes:
        - addColumn:
            tableName: study_environment_config
            columns:
              - column: { name: use_dev_dsm_realm, type: boolean, defaultValueBoolean: true, constraints: { nullable: false} }
              - column: { name: use_stub_dsm, type: boolean, defaultValueBoolean: true, constraints: { nullable: false} }
        - addDefaultValue:
            tableName: study_environment_config
            columnName: accepting_proxy_enrollment
            defaultValueBoolean: false
        - addNotNullConstraint:
            tableName: study_environment_config
            columnName: accepting_proxy_enrollment
