# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  deploymentZone: ${DEPLOYMENT_ZONE:local}
  db:
    host: ${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    name: ${DATABASE_NAME:pearl}
    password: ${DATABASE_USER_PASSWORD:dbpwd}
    user: ${DATABASE_USER:dbuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  sam:
    basePath: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
  tdr:
    basePath: ${TDR_ADDRESS:https://jade.datarepo-dev.broadinstitute.org}
    serviceAccountCreds: ${TDR_SA_CREDS:}
    storageAccountName: ${TDR_EXPORT_STORAGE_ACCOUNT_NAME:}
    storageAccountKey: ${TDR_EXPORT_STORAGE_ACCOUNT_KEY:}
    storageContainerName: ${TDR_EXPORT_STORAGE_CONTAINER_NAME:}
    billingProfileId: ${BILLING_PROFILE_ID:550212cf-45dc-478f-9fe6-9b3290e2a1fe}
    tdrExportEnabled: ${TDR_EXPORT_ENABLED:false}
  dsm:
    useLiveDsm: ${USE_LIVE_DSM:false}
    basePath: ${DSM_ADDRESS:https://dsm-dev.datadonationplatform.org/dsm}
    issuerClaim: ${DSM_JWT_ISSUER:admin-d2p.ddp-dev.envs.broadinstitute.org}
    secret: ${DSM_JWT_SIGNING_SECRET:}
  populate:
    populate-from-classpath: true
  b2c:
    tenantName: ${B2C_TENANT_NAME:missing_tenant_name}
    clientId: ${B2C_CLIENT_ID:missing_client_id}
    policyName: ${B2C_POLICY_NAME:missing_policy_name}
  email:
    sendgridApiKey: ${SENDGRID_API_KEY:}
    supportEmailAddress: ${SUPPORT_EMAIL_ADDRESS:support@juniper.terra.bio}
  hostnames:
    participantUi: ${PARTICIPANT_UI_HOSTNAME:localhost:3001}
    participantApi: ${PARTICIPANT_API_HOSTNAME:localhost:8081}
    adminUi: ${ADMIN_UI_HOSTNAME:localhost:3000}
    adminApi: ${ADMIN_API_HOSTNAME:localhost:8080}


# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:../config/local-properties.yml;classpath:git.properties

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mimeTypes: text/css,application/javascript
  port: ${SERVER_PORT:8080}

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: d2p-admin
  application.version: ${javatemplate.version.gitHash:unknown}

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${env.db.password}
    url: jdbc:postgresql://${env.db.host}/${env.db.name}
    username: ${env.db.user}

  web:
    resources:
      cache:
        cachecontrol:
          maxAge: 0
          mustRevalidate: true
        useLastModified: false
      staticLocations: classpath:/api/,classpath:/static/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

    # As of Aug. 2022, 9.4 was the latest documented dialect version.
    # Keep this in mind when attempting to use postgresql 10+ features
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

hibernate:
  packages-to-scan: bio.terra.pearl.core.model

b2c:
  tenantName: ${env.b2c.tenantName}
  clientId: ${env.b2c.clientId}
  policyName: ${env.b2c.policyName}

javatemplate:
  ingress:
    # Default value that's overridden by Helm.
    domainName: localhost:8080

  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125

  sam:
    basePath: ${env.sam.basePath}

terra.common:
  kubernetes:
    inKubernetes: false

  tracing:
    stackdriverExportEnabled: ${env.tracing.exportEnabled}
    samplingRate: ${env.tracing.samplingRate}
