apiVersion: v1
kind: Service
metadata:
  name: admin-service
  annotations:
    cloud.google.com/backend-config: '{"default": "juniper-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
