{{$adminUrl := .Values.adminUrl}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: admin-cert
spec:
  domains:
    - {{ .Values.adminUrl }}
    - www.{{ .Values.adminUrl }}
    {{- range .Values.portals }}
    - {{.}}.{{$adminUrl}}
    - sandbox.{{.}}.{{$adminUrl}}
    - irb.{{.}}.{{$adminUrl}}
    {{ end }}
