{{- define "customer-certs" -}}
{{- range $idx, $val := $.Values.portals -}}
{{- if $idx }}
{{- print ","  -}}
{{- end -}}
{{- $val.name -}}-admin-subdomain-cert{{if $val.customDomain}},{{- $val.name -}}-public-url-cert{{end}}
{{- end -}}
{{- end -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juniper-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: admin-ip
    networking.gke.io/managed-certificates: "admin-cert,{{ template "customer-certs" . }}"
    networking.gke.io/v1beta1.FrontendConfig: "juniper-frontend-config"
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: {{ .Values.adminUrl }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-service
                port:
                  number: 80
  defaultBackend:
    service:
      name: participant-service
      port:
        number: 80
