{{range .Values.studyCertificates}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{.groupName}}-public-url-cert
spec:
  domains:
    {{- range .urls }}
      - {{.}}
      - www.{{.}}
      - sandbox.{{.}}
      - irb.{{.}}
    {{- end }}
---
{{end}}
