#!/bin/sh
SERVER_NAME="localhost:8080"
set -u

# Fake access token for dbush@broadinstitute.org, generated by CurrentUnauthedUserService.generateFakeJwtToken
ACCESS_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJlbWFpbCI6ImRidXNoQGJyb2FkaW5zdGl0dXRlLm9yZyIsInRva2VuIjoiNzJjZDQyZTgtMWE0ZS00Nzg5LWFmODQtZDIwMDgxY2JlNWJjIn0."
# uncomment the below line to use a real Azure B2C token  (needed for populating anywhere other than localhost)
# ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
for portal in "$@"
do
  curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" "$SERVER_NAME/api/internal/v1/populate/portal?filePathName=portals/$portal/portal.json&overwrite=true"
  echo ""
done
