# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: ${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    name: ${DATABASE_NAME:pearl}
    password: ${DATABASE_USER_PASSWORD:dbpwd}
    user: ${DATABASE_USER:dbuser}
  email:
    sendgridApiKey: ${SENDGRID_API_KEY:}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:../config/local-properties.yml;classpath:git.properties

logging.pattern.level: '%X{requestId} %5p'

spring:
  cloud:
    gcp:
      secretmanager:
        enabled: ${ENABLE_GCP_SECRET_MANAGER:false}

  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: pearlcore
  application.version: ${pearlcore.version.gitHash:unknown}

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${env.db.password}
    url: jdbc:postgresql://${env.db.host}/${env.db.name}
    username: ${env.db.user}

liquibase:
  change-log: db/changelog/db.changelog-master.xml

terra.common:
  kubernetes:
    inKubernetes: false


