package bio.terra.pearl.core.service.participant;

import bio.terra.pearl.core.service.exception.internal.InternalServerException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.InputStream;
import java.util.HashSet;
import java.util.Optional;
import java.util.Scanner;
import java.util.Set;
import java.util.function.Function;
import java.util.function.Supplier;

@Service
@Slf4j
public class ShortcodeService {
    public static final String ALLOWED_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public static final String ALLOWED_NUMBERS = "0123456789";
    public static final int SHORTCODE_LENGTH = 6;
    public static final String PROFANITY_LIST_PATH = "profanity/bannedWords.txt";

    private final RandomUtilService randomUtilService;
    private Set<String> profanityList;

    public ShortcodeService(RandomUtilService randomUtilService) {
        this.randomUtilService = randomUtilService;
        this.profanityList = loadProfanityList();
    }

    public Set<String> loadProfanityList() {
        ClassPathResource resource = new ClassPathResource(PROFANITY_LIST_PATH);
        profanityList = new HashSet<>();
        try (InputStream bannedWordsStream = resource.getInputStream();
             Scanner scanner = new Scanner(bannedWordsStream)) {
            while (scanner.hasNextLine()) {
                profanityList.add(scanner.nextLine().trim());
            }
        } catch (Exception e) {
            // Log this as an error, but don't treat it as fatal.
            // return an empty set so that we can continue generating shortcodes
            log.error("Unable to load profanity list. Shortcodes will still be generated, but may contain profanity.", e);
            return Set.of();
        }
        return profanityList;
    }

    //this is pretty naively implemented. if performance ends up being an issue, we can
    //look into more efficient means of string matching
    public boolean isShortcodeBanned(String possibleShortcode) {
        for (String word : profanityList) {
            if (possibleShortcode.toLowerCase().contains(word.toLowerCase())) {
                return true;
            }
        }
        return false;
    }

    private String randomShortcodeGenerator() {
        return randomUtilService.generateSecureRandomString(SHORTCODE_LENGTH, ALLOWED_CHARS);
    }

    private String randomResearchIDGenerator() {
        return randomUtilService.generateSecureRandomString(2, ALLOWED_NUMBERS) + randomUtilService.generateSecureRandomString(4, ALLOWED_CHARS);

    }

    @Transactional
    public <T> String generateShortcode(
            String prefix,
            Function<String, Optional<T>> findOneByShortcode
    ) {
        return generateUniqueIdentifier(
                prefix,
                this::randomShortcodeGenerator,
                findOneByShortcode
        );
    }

    @Transactional
    public <T> String generateResearchId(
            String prefix,
            Function<String, Optional<T>> findOneByResearchId
    ) {
        return generateUniqueIdentifier(
                prefix,
                this::randomResearchIDGenerator,
                findOneByResearchId
        );
    }

    /**
     * Generate a unique shortcode. The shortcode is generated by concatenating the prefix with a random string.
     * It's possible there are snazzier ways to get postgres to generate this for us,
     * but for now, just keep trying strings until we get a unique one.
     * throws InternalServerException if, after 10 tries, a shortcode still couldn't be found.
     */
    protected <T> String generateUniqueIdentifier(
            String prefix,
            Supplier<String> generateRandomId,
            Function<String, Optional<T>> findOneById) {
        final int MAX_TRIES = 10;
        for (int tryNum = 0; tryNum < MAX_TRIES; tryNum++) {
            String possibleId = generateRandomId.get();

            if (isShortcodeBanned(possibleId)) {
                log.info("Attempted to generate shortcode with profanity: {} (retry attempt {})", possibleId, tryNum);
                continue;
            }

            if (prefix != null && !prefix.isEmpty()) {
                possibleId = prefix + "_" + possibleId;
            }

            if (findOneById.apply(possibleId).isEmpty()) {
                return possibleId;
            }
        }
        throw new InternalServerException("Unable to generate unique shortcode");
    }
}

