CREATE DATABASE pearl;
CREATE ROLE dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
GRANT CREATE ON DATABASE pearl to dbuser;

CREATE DATABASE pearl_test;
CREATE ROLE test_dbuser WITH LOGIN ENCRYPTED PASSWORD 'dbpwd';
GRANT CREATE ON DATABASE pearl_test to test_dbuser;
