name: End-to-end tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: dbpwd
          POSTGRES_USER: dbuser
          POSTGRES_DB: pearl

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build applications
      run: |
        ./scripts/run_dockerized.sh participant
        ./scripts/run_dockerized.sh admin
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm -w e2e-tests test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          e2e-tests/playwright-report/**
          e2e-tests/test-results/**
    - name: Notify slack on failure
      uses: broadinstitute/action-slack@v3.8.0
      if: failure() # && github.ref == 'refs/heads/development' #only notify on merges to development
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        channel: '#juniper-dev-notifications'
        status: failure
        author_name: End-to-end failed on merge to development
        fields: job
        text: "End-to-end tests failed :sadpanda:"
        username: 'Juniper Build Notifications'
