name: Push image to juniper-eng-infra
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - cb-github-action-fix-permissions
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: broad-juniper-eng-infra
  GOOGLE_DOCKER_REPOSITORY: us-central1-docker.pkg.dev
  IMAGE_REPOSITORY_NAME: juniper

jobs:
  get-version-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: perm-test # ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout Current Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: Parse Tag
        id: tag
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT

  publish-admin-image:
    needs: get-version-tag
    permissions:
      contents: 'read'
      id-token:  'write'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.juniper-eng-build-publish.outputs.published-image }}
    steps:
      - name: Checkout Current Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: build and publish image
        id: juniper-eng-build-publish
        uses: ./.github/actions/juniper-eng-build-push-image
        with:
          version-tag: ${{ needs.get-version-tag.outputs.tag }}
          image-repo: 'us-central1-docker.pkg.dev'
          image-name: "broad-juniper-eng-infra/juniper/${{ github.event.repository.name }}-admin"
          gradle-build-args: ':api-admin:jibDockerBuild'
    
  publish-participant-image:
    needs: get-version-tag
    permissions:
      contents: 'read'
      id-token:  'write'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.juniper-eng-build-publish.outputs.published-image }}
    steps:
      - name: Checkout Current Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: build and publish image
        id: juniper-eng-build-publish
        uses: ./.github/actions/juniper-eng-build-push-image
        with:
          version-tag: ${{ needs.get-version-tag.outputs.tag }}
          image-repo: 'us-central1-docker.pkg.dev'
          image-name: "broad-juniper-eng-infra/juniper/${{ github.event.repository.name }}-participant"
          gradle-build-args: ':api-participant:jibDockerBuild'
