name: Require ticket

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  require_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check for ticket in PR title
        id: validate
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const regex = /JN|DDO-\d+/;
            if (!regex.test(title)) {
              core.setFailed("PR title must contain a Jira ticket");
            }
