name: 'Java Test Report'

on:
  workflow_run:
    workflows: ['Java CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit Tests
          path: >
            api-admin/build/test-results/test/*.xml,
            api-participant/build/test-results/test/*.xml,
            core/build/test-results/test/*.xml,
            populate/build/test-results/test/*.xml
          reporter: java-junit
