name: UI CI

on:
  push:
    branches: [ development ]
    paths-ignore: [ '*.md']
  pull_request:
    branches: [ '**' ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Notify slack on failure
        uses: broadinstitute/action-slack@v3.8.0
        if: failure() && github.ref == 'refs/heads/development'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#juniper-dev-notifications'
          status: failure
          author_name: UI CI build failed on merge to development
          fields: job
          text: "UI CI build failed :sadpanda:"
          username: 'Pearl Build Notifications'
